### ISSUE TITLE
TypeError when using agenda with SailsJS

### ISSUE THREAD

**Issue by michaelpurnell** [rschmukler/agenda#160]
Hi I'm new to using Agenda.JS, I have the following small code. 

var Agenda = require('agenda');

var agenda = new Agenda();

agenda.define('printout', function(job, done) {
    console.log("I print a report!");
    done();
});

agenda.processEvery('3 seconds', 'printout');
agenda.start();

But I'm receiving an Type error below. Am i missing any dependencies or anything else?

/Desktop/appapi/node_modules/agenda/lib/agenda.js:260
  this._db.findAndModify(
          ^
TypeError: Cannot read property 'findAndModify' of undefined
    at Agenda._findAndLockNextJob (Desktop/appapi/node_modules/agenda/lib/agenda.js:260:11)
    at jobQueueFilling (Desktop/appapi/node_modules/agenda/lib/agenda.js:350:10)
    at processJobs (Desktop/appapi/node_modules/agenda/lib/agenda.js:334:7)
    at process._tickDomainCallback (node.js:381:11)

**Comment by ilanbiala** [comment]
You have to pass in an object with a db field. See the setup https://github.com/rschmukler/agenda.

**Comment by michaelpurnell** [comment]
Thanks this issue can close now.
