### ISSUE TITLE
agenda.every Crash

### ISSUE THREAD

**Issue by DQvsRA** [rschmukler/agenda#181]
This is my setup:
var agenda = new Agenda();
agenda.name("Backups").database(mongourl, "agenda");
agenda.define('backup_events', function(job, done) {
       backup.now(null, done)  
 });
agenda.every('15 seconds', 'backup_events');

and i use mongodb native drive only
"dependencies": {
    "agenda": "*",
    "body-parser": "~1.8.1",
    "bson": "^0.4.7",
    "cookie-parser": "~1.3.3",
    "debug": "~2.0.0",
    "express": "~4.9.0",
    "hbs": "~2.7.0",
    "jade": "*",
    "jsonfile": "*",
    "less-middleware": "1.0.x",
    "mega": "*",
    "moment": "^2.10.3",
    "moment-timezone": "^0.4.0",
    "mongodb": "*",
    "morgan": "~1.3.0",
    "pmx": "*",
    "q": "*",
    "serve-favicon": "~2.1.3"
  }

And that is what i got when run node app

D:\myproject>node app
Express server listening on port 3000
MongoError: Invalid modifier specified $setOnInsert
    at Object.toError (D:\myproject\node_modules\agenda\node_
modules\mongodb\lib\mongodb\utils.js:114:11)
    at D:\myproject\node_modules\agenda\node_modules\mongodb\
lib\mongodb\db.js:1196:31
    at D:\myproject\node_modules\agenda\node_modules\mongodb\
lib\mongodb\db.js:1905:9
    at Server.Base._callHandler (D:\myproject\node_modules\ag
enda\node_modules\mongodb\lib\mongodb\connection\base.js:453:41)
    at D:\myproject\node_modules\agenda\node_modules\mongodb\
lib\mongodb\connection\server.js:488:18
    at MongoReply.parseBody (D:\myproject\node_modules\agenda
\node_modules\mongodb\lib\mongodb\responses\mongo_reply.js:68:5)
    at null.<anonymous> (D:\myproject\node_modules\agenda\nod
e_modules\mongodb\lib\mongodb\connection\server.js:446:20)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (D:\myproject\node_modules\agenda\nod
e_modules\mongodb\lib\mongodb\connection\connection_pool.js:207:13)

???

**Comment by DQvsRA** [comment]
But if i use this setup:

var agenda = new Agenda();
agenda.name("Backups").database(mongourl, "agenda");
agenda.define('backup_events', function(job, done) {
          console.log("> Backup Events: Job Starts at", new Date());
          backup.now(null, done);
     });
agenda.jobs({ name: 'backup_events'}, function(err, jobs) {
          console.log(jobs);
          if(jobs.length == 0) {
               var job = agenda.create('backup_events');
               job.repeatAt('0:01am');
               //job.repeatEvery('one days');
               job.save();
          }
          agenda.start();
     });

It's work fine

**Comment by typpo** [comment]
Same problem here, using agenda@0.6.28.

I define 2 tasks, use `agenda.every('1 minute', 'foo bar');`, and then `agenda.start()` immediately crashes.

Any ideas here?

```
/home/ian/cc/node_modules/agenda/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;      
              ^
MongoError: Invalid modifier specified $setOnInsert
    at Object.toError (/home/ian/cc/node_modules/agenda/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /home/ian/cc/node_modules/agenda/node_modules/mongodb/lib/mongodb/db.js:1196:31
    at /home/ian/cc/node_modules/agenda/node_modules/mongodb/lib/mongodb/db.js:1905:9
    at Server.Base._callHandler (/home/ian/cc/node_modules/agenda/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /home/ian/cc/node_modules/agenda/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
    at MongoReply.parseBody (/home/ian/cc/node_modules/agenda/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/home/ian/cc/node_modules/agenda/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
    at emit (events.js:95:17)
    at null.<anonymous> (/home/ian/cc/node_modules/agenda/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
    at emit (events.js:98:17)
    at Socket.<anonymous> (/home/ian/cc/node_modules/agenda/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
DEBUG: Program node cc_app.js exited with code 8
```

**Comment by typpo** [comment]
Follow up: this happens when your mongo version is < 2.4.  Run `mongod --version` to check your version.

**Comment by nwkeeley** [comment]
Documentation indicates that you need Mongo 2.4+. Anything < 2.4 is not supported.

[In the ReadMe.md](https://github.com/rschmukler/agenda#installation)
