### ISSUE TITLE
Mongo `findAndModify` of undefined in 0.7.2

### ISSUE THREAD

**Issue by chrisjhoughton** [rschmukler/agenda#222]
Just tried upgrading to 0.7.2, on start up I got this stack trace error:

```
TypeError: Cannot read property 'findAndModify' of undefined
    at Agenda.saveJob (/Users/chris/Dropbox/Sauce/repos/group-worker/node_modules/agenda/lib/agenda.js:277:21)
    at Job.save (/Users/chris/Dropbox/Sauce/repos/group-worker/node_modules/agenda/lib/job.js:217:15)
    at createJob (/Users/chris/Dropbox/Sauce/repos/group-worker/node_modules/agenda/lib/agenda.js:192:9)
    at Agenda.every (/Users/chris/Dropbox/Sauce/repos/group-worker/node_modules/agenda/lib/agenda.js:182:12)
    at /Users/chris/Dropbox/Sauce/repos/group-worker/lib/batchSync.js:100:14
```

**Comment by chrisjhoughton** [comment]
Ignore this - just seen the docs have changed so `agenda.on('ready', cb)` needs to be used.

Would be good to have a changelog? I just upgraded as a result of https://github.com/rschmukler/agenda/issues/201, I'm sure others will hit this issue.
