### ISSUE TITLE
MongoError: no such cmd: crateIndexes 

### ISSUE THREAD

**Issue by yuniers** [rschmukler/agenda#247]
Recently I updated to version 0.7.5 and when I try start server an error is triggered.
I use others packages that use mongo and not cause problems.
My installed Mongodb version is 2.4.14.
Can anybody tell me if the error is of agenda of mine?

```
Mean app started on port 3003 (development) cluster.worker.id: 0
(node) crypto.createCredentials is deprecated. Use tls.createSecureContext instead.

/trabajo/klnda/node_modules/agenda/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^
MongoError: no such cmd: createIndexes
    at Function.MongoError.create (/trabajo/klnda/node_modules/agenda/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at /trabajo/klnda/node_modules/agenda/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:777:66
    at Callbacks.emit (/trabajo/klnda/node_modules/agenda/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/trabajo/klnda/node_modules/agenda/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:249:23)
    at Socket.<anonymous> (/trabajo/klnda/node_modules/agenda/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:265:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by nwkeeley** [comment]
Agenda requires Mongo 2.6+

https://github.com/rschmukler/agenda#installation

**Comment by yuniers** [comment]
@nwkeeley thank you, I not have seen the requirement on this page.

**Comment by rkmax** [comment]
@yuniers I just start using agenda 0.7.6 and I got the same issue

node 5.4.0
agenda 0.7.6
mongo 3.2.0
