### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by beingmohit** [rschmukler/agenda#287]
root@api:~/app# npm install agenda --save

> kerberos@0.0.18 install /home/ubuntu/hosts/api.adzem.com/node_modules/agenda/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory `/home/ubuntu/hosts/api.adzem.com/node_modules/agenda/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory `/home/ubuntu/hosts/api.adzem.com/node_modules/agenda/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-74-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/hosts/api.adzem.com/node_modules/agenda/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
agenda@0.8.0 node_modules/agenda
├── human-interval@0.1.5
├── date.js@0.2.2 (debug@0.7.4)
├── moment-timezone@0.5.0
├── cron@1.0.9 (moment-timezone@0.3.1)
└── mongodb@2.0.34 (readable-stream@1.0.31, mongodb-core@1.2.0)

**Comment by beingmohit** [comment]
Solved by running:
**sudo apt-get install libkrb5-dev**
