### ISSUE TITLE
Error: key $__ must not start with '$'

### ISSUE THREAD

**Issue by TimPchelintsev** [rschmukler/agenda#337]
Hi. I am trying agenda now but got this error. First I think it is because of mongo version(using 3.2), so I 
reinstall agenda with ```npm install git+https://git@github.com/philbrookes/agenda.git#RHMAP-7365``` but this didn't help. Can you please shed some light on this..
Traceback:
```javascript
.../node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^
Error: key $__ must not start with '$'
    at Error (native)
    at serializeInto (/Users/timofey/Projects/instalytics/node_modules/agenda/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:680:19)
    at serializeObject (/Users/timofey/Projects/instalytics/node_modules/agenda/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:280:18)
    at serializeInto (/Users/timofey/Projects/instalytics/node_modules/agenda/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:705:17)
    at serializeObject (/Users/timofey/Projects/instalytics/node_modules/agenda/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:280:18)
    at serializeInto (/Users/timofey/Projects/instalytics/node_modules/agenda/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:705:17)
    at serializeObject (/Users/timofey/Projects/instalytics/node_modules/agenda/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:280:18)
    at serializeInto (/Users/timofey/Projects/instalytics/node_modules/agenda/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:551:17)
    at serializeObject (/Users/timofey/Projects/instalytics/node_modules/agenda/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:280:18)
    at serializeInto (/Users/timofey/Projects/instalytics/node_modules/agenda/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:705:17)
    at [object Object].serialize (/Users/timofey/Projects/instalytics/node_modules/agenda/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/bson.js:47:27)
    at [object Object].Query.toBin (/Users/timofey/Projects/instalytics/node_modules/agenda/node_modules/mongodb/node_modules/mongodb-core/lib/connection/commands.js:146:25)
    at executeSingleOperation (/Users/timofey/Projects/instalytics/node_modules/agenda/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:1160:31)
    at [object Object].Server.command (/Users/timofey/Projects/instalytics/node_modules/agenda/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:1241:3)
    at executeWrite (/Users/timofey/Projects/instalytics/node_modules/agenda/node_modules/mongodb/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:60:12)
    at [object Object].WireProtocol.insert (/Users/timofey/Projects/instalytics/node_modules/agenda/node_modules/mongodb/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:68:3)
    at [object Object].Server.insert (/Users/timofey/Projects/instalytics/node_modules/agenda/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:1269:37)
    at [object Object].Server.insert (/Users/timofey/Projects/instalytics/node_modules/agenda/node_modules/mongodb/lib/server.js:351:17)
    at insertDocuments (/Users/timofey/Projects/instalytics/node_modules/agenda/node_modules/mongodb/lib/collection.js:696:19)
    at insertOne (/Users/timofey/Projects/instalytics/node_modules/agenda/node_modules/mongodb/lib/collection.js:408:3)
    at [object Object].Collection.insertOne (/Users/timofey/Projects/instalytics/node_modules/agenda/node_modules/mongodb/lib/collection.js:396:44)
    at [object Object].Agenda.saveJob (/Users/timofey/Projects/instalytics/node_modules/agenda/lib/agenda.js:367:22)
```

**Comment by TimPchelintsev** [comment]
It seems I got it. I tried to send an mongoose instance to job as an argument. Giving it and id instead of instance solved my issue. Thanks for great lib!

**Comment by TimPchelintsev** [comment]
First I think I managed to fix it, but now it returns. When I pass objectId as a string via data attribute, 
everything seems fine. But then, when I use my Mongoose model method .findById to get the actual instance I got the same error as in my initial message.
