### ISSUE TITLE
TypeError: Cannot read property 'findAndModify' of undefined

### ISSUE THREAD

**Issue by Neoflash1979** [rschmukler/agenda#435]
Just getting started with Agenda so I made a little test file to try it out. Here is my code:

```
const dburl = 'mongodb://localhost:27017/nightlife';
const url = process.env.MONGOLAB_URI;

import * as Agenda from 'agenda';

const agenda = new Agenda({
  db: { address: url || dburl, collection: 'agendaJobs' },
  processEvery: '1 minute'
});

agenda.define('print to console', function (job, done) {
  console.log('Job just fired');
});

agenda.every('15 seconds', 'print to console')

agenda.on('ready', function () {
  agenda.start();
});

function graceful() {
  agenda.stop(function () {
    process.exit(0);
  });
}

process.on('SIGTERM', graceful);
process.on('SIGINT', graceful);
```
And here is the error I'm getting when I run the file:

```
C:\Users\phili\Documents\Projects\FreeCodeCamp\nightlife\node_modules\agenda\lib\agenda.js:356
    this._collection.findAndModify({name: props.name, type: 'single'}, {}, update, {upsert: true, new: true}, processDbResult);
                    ^

TypeError: Cannot read property 'findAndModify' of undefined
    at Agenda.saveJob (C:\Users\phili\Documents\Projects\FreeCodeCamp\nightlife\node_modules\agenda\lib\agenda.js:356:21)
    at Job.save (C:\Users\phili\Documents\Projects\FreeCodeCamp\nightlife\node_modules\agenda\lib\job.js:233:15)
    at createJob (C:\Users\phili\Documents\Projects\FreeCodeCamp\nightlife\node_modules\agenda\lib\agenda.js:236:9)
    at Agenda.every (C:\Users\phili\Documents\Projects\FreeCodeCamp\nightlife\node_modules\agenda\lib\agenda.js:226:12)
    at Object.<anonymous> (C:\Users\phili\Documents\Projects\FreeCodeCamp\nightlife\agenda.js:13:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by Neoflash1979** [comment]
So sorry about that. I realised my mistake. `agenda.every('15 seconds', 'print to console')` should have been inside the `agenda.on` callback.
